SET IDENTITY_INSERT [dbo].[JOUEUR] ON
INSERT INTO [dbo].[JOUEUR] ([IDJOUEUR], [NUMJO], [IDEQUIPE], [NOM], [PRENOM], [PHOTO], [COEFF], [AGE], [TAILLE], [POIDS], [POST]) VALUES (3000, 1, 1, 1, 1, N'JJ',1, 1, 1,1,1)
SET IDENTITY_INSERT [dbo].[JOUEUR] OFF
